### ISSUE TITLE
Use of pull requests

### ISSUE THREAD

**Issue by besarthoxhaj** [super4minions/WebApp#10]
I noticed you have committed directly from GitHub.

I think you should use always pull requests. They make it more easy to track down changes and give you the chance to add context to every modification.

Here a simple guide on how to use it: https://guides.github.com/introduction/flow/

**Comment by SupervisionT** [comment]
Yes sure, this is an important issue to be considered in the future.

We did this to fix some typo's and we'll use pull request next time for such issues.
